name: Run ResearchBloggerAgent

on:
  schedule:
    - cron: "0 12 * * 2"  # Run every Tuesday at 12:00 UTC
  workflow_dispatch:        # Manually trigger the workflow

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for caching)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: docker build -t research-blogger-agent .

    # Step 6: Run the agent with environment variables
    - name: Run the ResearchBloggerAgent
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.AGENT_GH_TOKEN }}
        BLOG_REPO: ${{ secrets.BLOG_REPO }}
        BLOG_PATH: ${{ secrets.BLOG_PATH }}
      run: |
        docker run --rm \
          -e OPENAI_API_KEY="${OPENAI_API_KEY}" \
          -e GITHUB_TOKEN="${AGENT_GH_TOKEN}" \
          -e BLOG_REPO="${BLOG_REPO}" \
          -e BLOG_PATH="${BLOG_PATH}" \
          research-blogger-agent \
          python3 -m agent.agent \
          --field "cybersecurity" \
          --summary_points "methods, results" \
          --style "conversational, 400 words" \


    # Step 6.1: Print Docker logs
    - name: print docker logs
      run: docker logs $(docker ps -lq)

    # Step 7: Clean up Docker
    - name: Clean up Docker
      run: docker system prune -f
